version: 2

models:
  - name: dim_customer
    description: Dimension table for customer details
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique 
      - name: region
        description: Region where the customer is located
  - name: fact_orders
    description: Fact table containing order transactions
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: product_id
        tests:
          - relationships:
              to: ref('dim_products')
              field: product_id

      
    